export const ADD_TASK = "ADD_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const LOADING_TASKS = "GET_TASKS";
export const LOADING_TASKS_SUCCSESS = "GET_TASK_SUCCSESS";
export const LOADING_TASKS_FAILURE = "LOADING_TASK_FAILURE";
